theme: jekyll-theme-minimal
title: Rodrigo Aroni Siquette
description: <br> <b> Let's work together </b> <br>
  <p class="view"><a href="https://www.linkedin.com/in/rodrigo-aroni-siquettea/">Visit my Linkedin Profile</a></p>
  <p class="view"><a href="https://siquette.github.io/cv/">Checkout my curriculum</a></p>
logo: https://raw.githubusercontent.com/siquette/agoravai/gh-pages/imagem/logo1.png
show_downloads: false
