title:  <div align= "center"> Rodrigo Aroni Siquette </div>
description: <br> <b> Let's work together </b> <br>
  <p class="view"><a href="https://siquette.github.io/cv//">Checkout my curriculum</a></p>
  <br><br>
  <p class="view"><a href="https://www.linkedin.com/in/rodrigo-aroni-siquette/">Visit my Linkedin Profile</a></p>
logo: https://raw.githubusercontent.com/siquette/agoravai/gh-pages/imagem/logo1.png
show_downloads: true
theme: jekyll-theme-minimal
