theme: jekyll-theme-minimal
title: Rodrigo Aroni Siquette
description: <br> Let's work together <br>
logo: https://raw.githubusercontent.com/siquette/agoravai/gh-pages/imagem/logo1.png
show_downloads: false
