theme: jekyll-theme-minimal
<br<br>
title: Rodrigo Aroni Siquette
description: <br> <b> Let's work together </b> <br>
logo: https://raw.githubusercontent.com/siquette/agoravai/gh-pages/imagem/logo1.png
show_downloads: false
